spring.application.name=Caryanam_Finserv

server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/vahanfinserv?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=vahanfinserv
spring.datasource.password=Vahan@Finserv#123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size= 25MB
spring.servlet.multipart.max-request-size= 25MB



spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=support@vahanfinserv.com
spring.mail.password=Kharadi@6006

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

whatsapp.access.token=EAAOalWInKosBR8wWWyeLZBcu8BZAK9VNz7MFGn4Y6AiiwvWQzvHXTHeZC6mMSPPGbJLqzE6EJQouDd6ewdC7VNhD1vBXEoOvKrkwgDqm3PJNEDF3MsLrvq6rjqEvCnTli1DZCNqEXFjZCDoTDwBogCDFoZADbmwHTtHV7stp3XUCvjO2I1iaxAQn6hvvBWHWNH9wZDZD
whatsapp.phone.number.id=1151015304766334

spring.mail.default-encoding=UTF-8

razorpay.key.id=rzp_live_T7jOPcFlsFDktS
razorpay.key.secret=IsPttZRNXorLFp5D23PxPAUc



