package com.finserv.enums;

public enum BankFeature {
    LOW_INTEREST_RATE,
    FAST_APPROVAL,
    DOORSTEP_SERVICE,
    QUICK_DISBURSEMENT,
    ONLINE_APPLICATION,
    FLEXIBLE_EMI,
    GOVERNMENT_TRUSTED,
    LOW_PROCESSING_FEE,
    LONG_TENURE,
    ZERO_FORECLOSURE_CHARGES,
    BALANCE_TRANSFER_AVAILABLE,
    PRE_APPROVED_LOAN,
    MINIMAL_DOCUMENTATION,
    INSTANT_ELIGIBILITY_CHECK,
    TOP_UP_LOAN_AVAILABLE
}
